/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package YtelAPIClient

import(
	"ytelapi_lib/configuration_pkg"
	"ytelapi_lib/usage_pkg"
	"ytelapi_lib/subaccount_pkg"
	"ytelapi_lib/account_pkg"
	"ytelapi_lib/email_pkg"
	"ytelapi_lib/recording_pkg"
	"ytelapi_lib/transcription_pkg"
	"ytelapi_lib/conference_pkg"
	"ytelapi_lib/phonenumber_pkg"
	"ytelapi_lib/carrier_pkg"
	"ytelapi_lib/dedicatedshortcode_pkg"
	"ytelapi_lib/sharedshortcode_pkg"
	"ytelapi_lib/sms_pkg"
	"ytelapi_lib/voice_pkg"
)


/*
 * Interface for the YTELAPI_IMPL
 */
type YTELAPI interface {
     Usage()                 usage_pkg.USAGE
     SubAccount()            subaccount_pkg.SUBACCOUNT
     Account()               account_pkg.ACCOUNT
     Email()                 email_pkg.EMAIL
     Recording()             recording_pkg.RECORDING
     Transcription()         transcription_pkg.TRANSCRIPTION
     Conference()            conference_pkg.CONFERENCE
     PhoneNumber()           phonenumber_pkg.PHONENUMBER
     Carrier()               carrier_pkg.CARRIER
     DedicatedShortCode()       dedicatedshortcode_pkg.DEDICATEDSHORTCODE
     SharedShortCode()       sharedshortcode_pkg.SHAREDSHORTCODE
     SMS()                   sms_pkg.SMS
     Voice()                 voice_pkg.VOICE
     Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the YTELAPI interaface returning YTELAPI_IMPL
 */
func NewYTELAPI(basicAuthUserName string, basicAuthPassword string) YTELAPI {
    ytelAPIClient := new(YTELAPI_IMPL)
    ytelAPIClient.config = configuration_pkg.NewCONFIGURATION()
    ytelAPIClient.config.SetBasicAuthUserName(basicAuthUserName)
    ytelAPIClient.config.SetBasicAuthPassword(basicAuthPassword)
    return ytelAPIClient
}
