/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package voice_pkg

import "ytelapi_lib/models_pkg"
import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the VOICE_IMPL
 */
type VOICE interface {
    CreateSendRVM (string, string, string, string, *string, *string, *string) (string, error)

    CreateViewCall (string) (string, error)

    CreateViewCallDetails (string) (string, error)

    CreateInterruptCall (string, *string, *string, models_pkg.Status1Enum) (string, error)

    CreateListCalls (*int64, *int64, *string, *string, *string) (string, error)

    CreateVoiceEffect (string, models_pkg.AudioDirectionEnum, *float64, *float64, *float64, *float64, *float64) (string, error)

    CreatePlayAudio (string, string, string, *int64, models_pkg.Direction1Enum, *bool) (string, error)

    CreateRecordCall (string, bool, models_pkg.DirectionEnum, *int64, *string, models_pkg.FileformatEnum) (string, error)

    CreatePlayDTMF (string, string, models_pkg.PlayDtmfDirectionEnum) (string, error)

    CreateGroupCall (string, string, string, string, models_pkg.GroupConfirmFileEnum, *string, *string, *string, *string, *string, *string, *string, *int64, *string, *string, *bool, *string, *string, *bool, *string) (string, error)

    CreateMakeCall (string, string, string, *string, *string, *string, *string, *string, *string, *string, *int64, *string, *bool, *bool, *string, *string, *bool, *string, models_pkg.IfMachineEnum, *string, *string, *bool, *string) (string, error)
}

/*
 * Factory for the VOICE interaface returning VOICE_IMPL
 */
func NewVOICE(config configuration_pkg.CONFIGURATION) *VOICE_IMPL {
    client := new(VOICE_IMPL)
    client.config = config
    return client
}