/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package phonenumber_pkg

import "ytelapi_lib/models_pkg"
import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the PHONENUMBER_IMPL
 */
type PHONENUMBER interface {
    CreateBulkBuyNumbers (models_pkg.NumberType2Enum, string, string, *string) (string, error)

    CreateBulkUpdateNumbers (string, string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (string, error)

    CreateMoveNumber (string, string, string) (string, error)

    CreateListNumbers (*int64, *int64, models_pkg.NumberTypeEnum, *string) (string, error)

    UpdateNumber (string, string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (string, error)

    CreateViewDetails (string) (string, error)

    CreateReleaseNumber (string) (string, error)

    CreatePurchaseNumber (string) (string, error)

    CreateGetDIDScore (string) (string, error)

    CreateAvailableNumbers (models_pkg.Numbertype1Enum, string, *int64) (string, error)

    CreateBulkRelease (string) (string, error)
}

/*
 * Factory for the PHONENUMBER interaface returning PHONENUMBER_IMPL
 */
func NewPHONENUMBER(config configuration_pkg.CONFIGURATION) *PHONENUMBER_IMPL {
    client := new(PHONENUMBER_IMPL)
    client.config = config
    return client
}